config/routes.rb
TravelBuddy::Application.routes.draw do
  devise_for :users, controllers: {omniauth_callbacks: "omniauth_callbacks"}
  resources :users
  resources :reservations
  resources :trips, only: [:index, :create, :destroy]

  root :to => "static#home"

  get "trips/new"
  get "trips/index"
  post "trips/create"
  post "trips/reserve"
  get "static/home"

end

app/models/reservation.rb
class Reservation < ActiveRecord::Base
  belongs_to :user
  belongs_to :trip

  attr_accessible :user_id, :trip_id

  def create

  end

  def new

  end
end

app/models/trip.rb
class Trip < ActiveRecord::Base

  has_many :reservations
  has_many :users, :through => :reservations

  default_scope order('date ASC')

  attr_accessible :lat_dest, :lng_dest, :lat_local, :lng_local, :date, :location_start, :location_end, :time, :vehicle, :mpg, :seats_available, :distance,:user_id, :cost

  def delete
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable

  has_many :reservations
  has_many :trips, :through => :reservations

  devise :database_authenticatable, :registerable, :omniauthable,
         :recoverable, :rememberable, :trackable, :validatable

  attr_accessible :email, :password, :password_confirmation, :remember_me, :username, :image, :phone_number, :about_me
  validates_presence_of :username, :email, :image, :phone_number
  validates_uniqueness_of :email#, :phone_number
  validates :username, uniqueness: true,
                       format: { with: /\A[a-zA-Z0-9]+\z/, message: "username can only contain letters and numbers"}

  #carrierwave
  mount_uploader :image, ImageUploader

  def self.from_omniauth(auth)
    where(auth.slice(:provider, :uid)).first_or_create do |user|
      user.provider = auth.provider
      user.uid = auth.uid
      user.username = auth.info.nickname
      user.image = auth.info.image
    end
  end

  def self.new_with_session(params, session)
    if session["devise.user_attributes"]
      new(session["devise.user_attributes"], without_protection: true) do |user|
        user.attributes = params
        user.valid?
      end
    else
      super
    end
  end

  def update_with_password(params, *options)
    if encrypted_password.blank?
      update_attributes(params, *options)
    else
      super
    end
  end

  def password_required?
    super && provider.blank?
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << [:image, :username, :phone_number, :about_me]
    devise_parameter_sanitizer.for(:account_update) << [:image, :username, :phone_number, :about_me]
  end
end

app/controllers/omniauth_callbacks_controller.rb
class OmniauthCallbacksController < Devise::OmniauthCallbacksController

  def all
    user = User.from_omniauth(request.env["omniauth.auth"])
    if user.persisted?
      sign_in_and_redirect user, notice: "signed in!"
    else
      session["devise.user_attributes"] = user.attributes
      redirect_to new_user_registration_url
    end
  end

  alias_method :twitter, :all
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
  before_action :authenticate_user!

  def create
    @reservation = Reservation.new(reservation_params)
    if @reservation.save
      trip = Trip.find(@reservation.trip_id)
      trip.seats_available = (trip.seats_available.to_i - 1).to_s

      if trip.save!
        user = User.find(trip.user_id)
        @twilio_client = Twilio::REST::Client.new 'AC364ef2ccd2c79070943d6644b2d573f8', 'abf7617908903c4830754a8102e0f457'
        @twilio_client.account.sms.messages.create(
          :from => "+16158612408",
          :to => "+1#{user.phone_number}",
          :body => "#{current_user.username} has just joined your trip from #{trip.location_start} to #{trip.location_end} on #{trip.date}"
        )
        redirect_to current_user
      end
    end
  end

  def destroy
    @reservation = Reservation.where(trip_id: params[:id]).where(user_id: current_user.id)
    res_trip = @reservation[0].trip_id
    if @reservation[0].destroy!
      trip = Trip.find(res_trip)
      trip.seats_available = (trip.seats_available.to_i + 1).to_s
      trip.save!
      redirect_to current_user
    end
  end


  private

  def reservation_params
    params.require(:reservation).permit(:trip_id, :user_id)
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    user = User.from_omniauth(env["omniauth.auth"])
    session[:user_id] = user.id
    redirect_to root_url
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url
  end

end

app/controllers/static_controller.rb
class StaticController < ApplicationController
  def home
  end
end

app/controllers/trips_controller.rb
class TripsController < ApplicationController

  before_action :authenticate_user!
  #before_action :correct_user, only: :destroy

  def index
    @search = Trip.search(params[:q])
    @trips = @search.result
  end

  def create
    @trip = current_user.trips.new(trip_params)
    @trip.starting_seats_available = trip_params[:seats_available]
    if @trip.save
      redirect_to current_user
    end
  end

  def destroy
    @trip = Trip.find(params[:id])
    @trip.destroy!
    redirect_to current_user
  end

  def reserve
  end

  private

  def trip_params
    params.require(:trip).permit(:lat_dest, :lng_dest, :lat_local, :lng_local, :date, :location_start, :location_end, :time, :vehicle, :mpg, :seats_available, :distance, :user_id, :cost)
  end
end

app/controllers/user_controller.rb
class UsersController < ApplicationController

  def show
    @user = User.find(params[:id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
before_filter :authenticate_user!

  def show
    @user = User.find(params[:id])
    @user_reservations = @user.reservations.map(&:trip)
    @my_trips = Trip.where(user_id: params[:id])
  end

  def remove
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/omniauth_callbacks_helper.rb
module OmniauthCallbacksHelper
end

app/helpers/reservations_helper.rb
module ReservationsHelper
end

app/helpers/static_helper.rb
module StaticHelper
end

app/helpers/trips_helper.rb
module TripsHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/layouts/_footer.html.haml
%footer.footer
  %small
    %a{:href => "http://github.com/finleysa"} COPILOT
  %nav
    %ul
      %li= link_to "About",  "#"
      %li= link_to "Contact", "#"
      %li
        %a{:href => "www.google.com/news"} News

app/views/layouts/_header.html.haml
.top-bar
  %ul.title-area
    %li.name= link_to "Copilot", root_path, id: "logo"
  %section.top-bar-section
    %ul.right
      - if user_signed_in?
        %li.divider
        %li= link_to 'Create Trip', trips_new_path
        %li.divider
        %li= link_to 'Search Trips', trips_index_path
        %li.divider
        %li= link_to "Logged in as #{current_user.email}", current_user
        %li.divider
        %li.has-form.has-dropdown.not-click
          %a.menu(href="#") Menu...
          %ul.dropdown
            %li.divider
            %li= link_to "Profile", current_user
            %li.divider
            %li= link_to 'Edit Profile', edit_user_registration_path
            %li.divider
            %li= link_to 'Logout', destroy_user_session_path, method: :delete
            %li.divider
      - else
        %li.divider
        %li= link_to "Sign up", new_user_registration_path
        %li.divider
        %li= link_to "Login", new_user_session_path
        %li.divider
        %li= link_to image_tag("bird.png", :border => 0), user_omniauth_authorize_path(:twitter)
        %li.divider

  /End top bar

app/views/layouts/application.html.haml
!!!
%html{:lang => "en"}
  %head
    %meta{:charset => "utf-8"}/
    %meta{:content => "width=device-width, initial-scale=1.0", :name => "viewport"}/
    %title Copilot
    = favicon_link_tag 'favicon.ico'
    %script{:src => "https://maps.googleapis.com/maps/api/js?key=AIzaSyAmN0r1eJV2qHS3UZUpS8ytISU7etkg0ZI", :type => "text/javascript"}
    = stylesheet_link_tag    "application"
    = javascript_include_tag "vendor/modernizr"
    = csrf_meta_tags
  %body
    #container
      = render 'layouts/header'
      = yield
      = render 'layouts/footer'
  = javascript_include_tag "application"

app/views/trips/index.html.haml
.row
  .large-6.columns.animated.bounceInLeft
    = search_form_for @search do |f|
      %fieldset
        %legend SEARCH!
        = f.label :location_start_cont, "Start Location"
        = f.text_field :location_start_cont
        = f.label :location_end_cont, "End Location"
        = f.text_field :location_end_cont
        = f.submit "Search", class: 'button button-block button-rounded button-royal button-large'
    %ul
    - @trips.limit(10).each do |trip|
      - if current_user.id != trip.user_id
        %li
          - date = /\d\d\d\d-\d\d-\d\d/.match(trip.date.to_s)
          %a.showGeo{"data-dropdown" => "drop#{trip.id}",:id => "#{trip.id}", :href => "#"} #{date} <span>#{trip.cost}</span> #{trip.location_start} --> #{trip.location_end}
        .f-dropdown.large{"data-dropdown-content" => "", :id => "drop#{trip.id}"}
          %a{href: "/users/#{trip.user_id}"}
            %h4 Trip Creator
          %h4{:href => "#"} <span>Vehicle:</span> #{trip.vehicle}
          %h4{:href => "#"} <span>Est. Gas Cost:</span> #{trip.cost}
          %h4{:href => "#"} <span>Distance:</span> #{trip.distance}
          %h4{:href => "#"} <span>Travel Time:</span> #{trip.time}
          %h4{:href => "#"} <span>Seats Available</span> #{trip.seats_available}
          - if trip.seats_available.to_i != 0
            = simple_form_for :reservation, :url => {:action => :create, :controller => 'reservations'} do |f|
              = f.input :trip_id, :as => :hidden, :input_html => { :value => "#{trip.id}" }
              = f.input :user_id, :as => :hidden, :input_html => { :value => current_user.id }
              = f.button :submit, class: 'button button-block button-rounded button-royal button-large'

          %label.hidden{:class => "latStart"} *#{trip.lat_local}
          %label.hidden{:class => "lngStart"} *#{trip.lng_local}
          %label.hidden{:class => "latEnd"} *#{trip.lat_dest}
          %label.hidden{:class => "lngEnd"} *#{trip.lng_dest}

  .large-6.columns.animated.bounceInRight
    #map.no_lr_margin

app/views/trips/new.html.haml
#map.animated.fadeInDownBig
#travel
  #travel_info
.row
  .large-4.columns.animated.fadeInUpBig
    #instructions
      %h2 Instructions
      %ol
        %li Fill out the form entirely
        %li Use only locations in the United States (City, State) or Canada if you must (City, Province)
        %li Click <span class="green">Geocode</span> button
        %li If you are satisfied with your trip click <span class="purple"> Save Trip</span>

  .large-8.columns.animated.fadeInRightBig
    = simple_form_for :trip, :url => {:action => :create} do |f|
      %fieldset
        .row.trip-info
          .large-4.columns
            = f.input :location_start, label: 'Starting City, State'
            = f.hidden_field :lat_local
            = f.hidden_field :lng_local
            = f.input :location_end, label: 'Destination'
            = f.hidden_field :lat_dest
            = f.hidden_field :lng_dest
            = f.hidden_field :distance
            = f.hidden_field :time
            = f.hidden_field :cost
            = f.hidden_field :user_id, :value => current_user.id
            %a{:id => 'geocode', :class => 'button button-3d-action button-pill'} Geocode
          .large-4.columns
            = f.input :vehicle
            = f.input :mpg
            = f.input :seats_available, :collection => 1..7
          .large-4.columns
            = f.input :date, as: :date

        = f.button :submit, class: 'button button-block button-rounded button-royal button-large'

app/views/trips/show.html.haml
.row
  .large-4.columns
    = search_form_for @search do |f|
      %fieldset
        %legend SEARCH!
        = f.label :location_start_cont, "Starting Location"
        = f.text_field :location_start_cont
    %ul
    - @trips.each do |trip|
      %li #{trip.location_start}
  .large-8.columns
    #map

app/views/user/show.html.haml
- if (current_user == @user)
  %h1 Your Profile
- else
  %h1 #{@user.username}'s Profile
%h3= @user.username
%h4= @user.email

- if current_user == @user
  Drafts

  %h1 You have squmbd:

-if current_user
  -if (current_user == @user)
    %h4 This is your profile

app/views/users/show.html.haml
.row
  .large-6.columns.animated.bounceInLeft
    %h1.center #{@user.username}'s Profile
    %h4.center= @user.email
    %fieldset
      .profile-image{:style => "background-image:url('#{@user.image_url.to_s}')"}

    /= image_tag @user.image_url.to_s, class: 'profile-image'

  .large-6.columns.animated.bounceInDown
    - if current_user == @user
      .space
      = link_to 'Edit Profile', edit_user_registration_path, class: "button button-3d-action button-large"
      .space
    - else
      .space
    - if @user.about_me
      %h3 About me:
      %p= @user.about_me

    /- if current_user == @user
.row
  .large-6.columns.animated.bounceInUp
    -if current_user
      %fieldset
        - if @my_trips.length > 0
          %h4 #{@user.username}'s Trips
          %table
            %tr
              %th Date
              %th Start Location
              %th End Location
              %th Est. Cost
              %th Seats Left
              - @my_trips.each do |a|
                -if a
                  /- if Time.now < a.date
                  - b=/\d\d\d\d-\d\d-\d\d/.match(a.date.to_s)
                  %tr
                    %td #{b}
                    %td #{a.location_start}
                    %td #{a.location_end}
                    %td #{a.cost}
                    %td #{a.seats_available}

                    - if a.user_id.to_s == current_user.id.to_s
                      %td= link_to 'Delete', a, method: :delete, :class => "button button-3d-caution button-tiny"

  .large-6.columns.animated.bounceInRight
    - if @user.trips.count > 0
      %fieldset
        %h4 Number of Trips Reserved: #{@user.trips.count}
        %table
          %tr
            %th Date
            %th Start Location
            %th End Location
            %th Est. Cost
            %th Total Seats
            - @user_reservations.each do |a|
              -if a
                /- if Time.now < a.date
                - b=/\d\d\d\d-\d\d-\d\d/.match(a.date.to_s)
                %tr
                  %td #{b}
                  %td #{a.location_start}
                  %td #{a.location_end}
                  %td #{a.cost}
                  %td #{a.starting_seats_available}
                  - if a.user_id.to_s == current_user.id.to_s
                    %td
                      %a{class: "button button-3d-caution button-tiny", controller: "reservations", "data-method" => "delete", href: "/reservations/#{a.id}", rel: "nofollow"} Delete